### ISSUE TITLE
Express - Get Another Quote Button not instantly working.

### ISSUE THREAD

**Issue by ambroseIT** [mayank30/gclparcel#1]
When you click on get another quote. It doesn't work until you click twice on the Get Another Quote icon.

**Comment by mayank30** [comment]
Just wait for 1-2 sec as it is getting data again for all countries for first screen ..

**Comment by mayank30** [comment]
BTW i fixed and will be live in next release. .. !!

**Comment by ambroseIT** [comment]
Awaiting retest once you install the new release

**Comment by ambroseIT** [comment]
1. After you have a DHL quote then attempt to get another quote.
2. Since the system is not clearing - then click on book.

- you will see the problem - all data are lost. (Big Bug)
That event of 1 & 2 should never happen, please.

Once a user says get a new quote then return to the beginning (Get a Quote). 


[Get Quote then CLick Book.zip](https://github.com/mayank30/gclparcel/files/2987121/Get.Quote.then.CLick.Book.zip)

**Comment by ambroseIT** [comment]
Agreed - now working fine - CLosed
