### ISSUE TITLE
Express - Documentation

### ISSUE THREAD

**Issue by ambroseIT** [mayank30/gclparcel#11]
InDirect Booking
A. User printer - email to user & generated after use pays. 
1. DHL Pick up label AWB
2. Consignee Address label - instruction put a copy inside your parcel & paste on the side of your parcel. 
3. Customer Order Receipt 
B. Admin printer 
1. final destination booking UK to worldwide using the client's address. Admin will always have daily dhl pick up booking... so don't worry it not your problem to do 2nd pickup schedule. Just generate docs
2. commercial invoice for countries outside EU. if UK leaves Brexit all countries need a commercial invoice 
3. total manifest of the day for all booking dhl pick up for that day - is good.

**Comment by mayank30** [comment]
Its already done !! 
As you can see we have two different type of Invoice attach to Order Section .. 

Online Order Receipt will be common for all types of Payment. its not specific to only Express. 
So that's the different and it will be email not a PDF.. 

@ambroseIT  2nd Pick up will be done by you by next document will be avaiable in admin panel .. so you can download and print for your self and stick on parcel and ship again .. 

hope all clear . !!

**Comment by ambroseIT** [comment]
**DOCUMENT** - Yes We only need 2 doccs for Express. 
a. Receipt & 
b. DHL AWB & commercial invoice for International shipments.
For now UK to EU doesn't need commercial invoice...maybe after BREXIT. UK to rest of the world needs it.
Nigeria to Worldwide needs commercial Invoice. 
____________________________________________________________________________________________________________
1. Yes Online Order invoice - email to the customer directly - AGREE.
2. AWB 
         a. For UK - Indirect logic remember. The user gets UK pickup from his/her Door to GCL UK office. 
         b. For Nigeria - Drop off  - Direct logic remember ...... since it controlled by Depot Admin. 
 

> From Nigeria                     
1. the user gets a NO pickup.
2. User Get quotes, books and pays Online
3. Select which branch office is close by for drop off
4. Brings the shipment with his payment invoice to us. 
4. Admin will check the shipment if weight is all fine - Admin prints the DHL AWB and manually initiate DHL pick up. (If you can email Admin the DHL booking fine, if No then save it somewhere where Admin can have access to find it and reprint.)

**Comment by ambroseIT** [comment]
DHL Indirect Documentation Defect ...................Please read the above 

[DHL Indirect Documentation Defect.docx](https://github.com/mayank30/gclparcel/files/3015047/DHL.Indirect.Documentation.Defect.docx)

**Comment by ambroseIT** [comment]
Today is 15/04/2019

I just booked a dhl shipment - system duplicated it as 140kg. 70kg each.
1. Paperwork for Indirect still wrong.
Leg 1
a. Receipt - Should show all details entered by the client, 
                 - Add a line: ROuting: (sender Postcode) to GCL Warehouse then to (Sender Postcode)  
                 - Add : Service: DHL Express
                 - Use GCL logo for the receipt, not DHL, please.
2. Pick up - label - Correct.

Leg 2.
If the details change and price is affected.
a. A new invoice of the difference is needed

Once payment is all cleared Admin will finish the final leg
3. Commercial invoice & Final Leg Airwaybill- Not available until after Admin books the shipment. 

Both Admin & User can now see both legs Airwaybill and all documentation. Any question?

Before the user pays for the service - we need to inform them the shipment will come to us first. either at the point of registration of something or at the of confirming your booking. 

> Insert in the summary page please & on the Receipt & Order confirmation email alert

Something like - I confirm I am aware that all parcels booked via my profile will go through GCL warehouse for reweighing and any discrepancy that affect my charges I agree to pay the difference.

**Comment by ambroseIT** [comment]
Note:

> 1. Direct Access: (Authorized Agent login Only)

a. UK to UK & EU (depending on Brexit) Commercial invoice not required.
b. Uk to Rest of the world - Commercial invoice required.
c. Nigeria to Worldwide - Commercial invoice is required. 

[GCLN000172     Airwaybill                Ibukun Ayodele           Benson    USA.pdf](https://github.com/mayank30/gclparcel/files/3234922/GCLN000172.Airwaybill.Ibukun.Ayodele.Benson.USA.pdf)
[GCLN000173     Airwaybill                Oluwatoyin Bxaruwa          Benson    USA.pdf](https://github.com/mayank30/gclparcel/files/3234923/GCLN000173.Airwaybill.Oluwatoyin.Bxaruwa.Benson.USA.pdf)
[GCLN00085    Airwaybill               Mr Adeyeye Festus           Benson      Cryprus.pdf](https://github.com/mayank30/gclparcel/files/3234925/GCLN00085.Airwaybill.Mr.Adeyeye.Festus.Benson.Cryprus.pdf)
[GCLN00119    Airwaybill             Mr Ismail Adedeji         Benson      Canada.pdf](https://github.com/mayank30/gclparcel/files/3234926/GCLN00119.Airwaybill.Mr.Ismail.Adedeji.Benson.Canada.pdf)

> Once a request is Internation for both Direct or Indirect. We need them to fill in all details required for us to process commercial invoice but don't make available for the Indirect user. Admin will use the details to rebook after weight checking. 

We are currently asking for declared value only, we need more info.

For customs purpose, we will need more clearly breakdown rather than a summary. 
Example....................
![image](https://user-images.githubusercontent.com/10438260/58599943-3c40a000-827a-11e9-9284-0f7d8fd704fe.png)

1. The first thing is that DHL is asking the user. 
*Create invoice or Use own invoice* ?  
![image](https://user-images.githubusercontent.com/10438260/58599688-40b88900-8279-11e9-849f-5510064000cb.png)

2. User ticks create invoice.
a. the shipper and consignee details auto-populated.
b. declaration entry required.
Qty, each value, each weight etc. then summarizes everything below. The total declared value must match the initial declared value. If No then display an error message for the user to attend to it. 

![image](https://user-images.githubusercontent.com/10438260/58599756-8c6b3280-8279-11e9-9d70-476dd04805a8.png)

3. Export ID drop down 
![image](https://user-images.githubusercontent.com/10438260/58599886-0bf90180-827a-11e9-98ad-53b61a44baa1.png)

4. Duty section 
![image](https://user-images.githubusercontent.com/10438260/58599967-55e1e780-827a-11e9-91ae-7e3fc9511667.png)
- Select customs terms of trade
![image](https://user-images.githubusercontent.com/10438260/58599981-65613080-827a-11e9-8fa4-fc710c394ba9.png)

- Resean for Export 
![image](https://user-images.githubusercontent.com/10438260/58600007-875ab300-827a-11e9-8901-2093dfac7dd7.png)
