### ISSUE TITLE
Air Cargo - UK to EU countries Static Rate

### ISSUE THREAD

**Issue by ambroseIT** [mayank30/gclparcel#12]
Check the DHL economy tab for UK to EU rate and also check the zone table for the EU countries and link up the zones.

No need to do API call to determine the UK to EU rate for Air Cargo as you are not making much fast progress.
................................Use below 
Nigeria Via  UK to EU
1. Agent : N1300 / Kg   + N2000 Handling fees   + the zone rate in the sheet 
2. Public: N1500 /KG    + N5000 Handling fees    + the zone rate in the sheet

We need where we can always manually enter todays exchange convertion rate by admin please.

today rate is N465 to £1. 

[Countries.xlsx](https://github.com/mayank30/gclparcel/files/2982354/Countries.xlsx)

**Comment by ambroseIT** [comment]
today rate is  £1 to N465  - selling  ........ when our rate is in Naira
today rate is N475 to £1 - buying ...... when our rate is in £

**Comment by mayank30** [comment]
https://docs.google.com/spreadsheets/d/1nMO7Dm_VbvHG7vXKSfXXmM0AXqtSGsdXP23qHT5DOYM/edit?usp=sharing

**Comment by mayank30** [comment]
As its is backend driven.. so can be managed accordingly .. 

Closing this ticket
