### ISSUE TITLE
Air Cargo - Nigeria to USA Static Rate

### ISSUE THREAD

**Issue by ambroseIT** [mayank30/gclparcel#13]
Agent
1. 1-10 KG 
a.  Nigeria to UK N1300/KG + £45  flat
2. 11KG to 30
a. Nigeria to UK N1300/KG + £4.20/kg
3. 31KG to 60
a. Nigeria to UK N1300/KG + £4.15/kg
3. 61KG to 80
a. Nigeria to UK N1300/KG + £4.05/kg
4. 81KG to 100
a. Nigeria to UK N1300/KG + £3.98/kg
5. 100Kg above
a. Nigeria to UK N1300/KG + £3.85/kg

Individual 
N1400 + UK to USA agent * 20%

**Comment by mayank30** [comment]
Backend driven can be managed by Admin .. code deployed .
