### ISSUE TITLE
General - Nigeria Depot Address 

### ISSUE THREAD

**Issue by ambroseIT** [mayank30/gclparcel#14]
Create a table to hold our depot address  UK & Nigeria, please.
We have 3 different locations in Nigeria. 
1. Lagos
  a. Depot ID G002 
  b. Location Code : LOS 
  c.  GCL Hub, 19 Gbemisola St, Allen, Ikeja, Nigeria.
  d. Country:  Nigeria.
  e. Depot Type: GCL Office
    f. Active : Y/N
    Available service - Express & Air Cargo

2. Ibadan
   a. Depot ID G001
   b. Location Code : IBA 
    c. Address:  GCL Shipping, 15 Funmi Fashion Centre, Odo-Ona Elewe Road, Orita Challenge Ibadan Oyo State. 
    d. Country:  Nigeria.
    e. Depot Type: GCL Office
      f. Active : Y/N
     Available service - Express & Air Cargo

3. Abuja 
     a. Depot ID A001 
     b. Location Code:    ABJ
     c. Address:  Suite SF6, BusyMArt Plaza. 44 Ebitu Ukiwe Street. Jabi Abuja Nigeria 
     d. Country:  Nigeria.
    e. Depot Type: AGent 
     f. Active : Y/N
      Available service - Express & Air Cargo

*Remember Nigeria Express* - Users have to visit our office. No pick up available. 

*Air Cargo*  USer can drop off &  pick up is available  (i am still negotiating on rate). To avoid delay in Go Live use drop off option for both express and air cargo for now plz. 

In UK no drop off ...... service. (Express & Airfreight )

**Comment by mayank30** [comment]
Send me the calculation from All the Depot to UK .. as it is gonna be used for NG to EU via UK & NG to US via UK.
