### ISSUE TITLE
Air Cargo UK to Worldwide (Airport Service)

### ISSUE THREAD

**Issue by ambroseIT** [mayank30/gclparcel#15]
> This service is only from UK to all Destination Airport Only
> 
*Get Quote* 
This is the same as you have done for UK to Nigeria...only adding more countries and ......it Airport driven.
  
1. The user will book from Uk address e.g. Rm9 5xr to India 200KG. He will declare value, pics, and content.  
(No dangerous goods & batteries allowed (x) )
(Enter agent service account (for the agent) ............)..............if you are an agent then verify once they log in. 

2. The System will return the total bill from UK Address to Available India Airport. 
*Advice user* (x) I confirm that the item(s) is palletized. If No we can not carry unpalletized item. Contact customer service for advice.
------
Then *User will follow normal *booking process* as previously discussed & pay*
------
3. The system will email Address label (Pick Up Address & GCL Address, HAWB number...a  unique GCL ref.... ) and Payment confirmation receipt to user.  

*Summary of the process*
So we will arrange collection from the users UK Address manually and send it directly to Airport (AMI Address with our reference and name & logo on the paperwork). 
Note- Booking submitted before 12 noon of a working day can be collected same day. 

KEY POINT
1. Minimum weight allowed is 60KG - anything lesser please use our Express service or contact customer service cs@gclparcel.com. 

2. Packaging: Pallet only (Palletized items)

3. User option: Door to Airport, GCL Office to Airport, Airport to Airport 

- [ ] 1.  Individual: UK Pick Up / Drop off at GCL UK Office Only.
- [ ] 2.  Agent: UK Pick Up / Drop off at GCL UK Office / Drop of at 2 Airport (LGW & MAN).

a. Where user select Door - pick up fee is charged + handling £20 or 0.30/kg whichever is higher + Freight Charges. 
b. Where the user selects GCL Office - No pick up fee charged + handling £40 or 0.50/kg whichever is higher + Freight Charges. 
c. Where user select Airport - No pickup fee charged + handling £20 or 0.20/kg whichever is higher + Freight Charges. 

4. Freight Charges: 
 a. Agent: the rate on the sheet * markup+ AMI fees £60 + (Pick Up/Drop Off) + Export Docs £15 + Xray fees £40. 
- Min weight of 150KG
- Pick Up/Drop Off: An agent has the option to deliver to Manchester airport MAN or London airport (LGW)
- markup below 300KG - *1.50, 301 to 500KG - *1.40, 501 to 1000KG - *1.35

b. Individual: the rate on the sheet * markup + AMI fees £65 + Pick Up + Export Docs £35 + Xray fees £40
- Min weight of 60KG
- Pick Up/Drop Off: Pick up & Office Drop off only. So pick up charge applicable. use the normal calculation for UK pickup please heavyweight. min of £85/pallet 60 to 150kg) 
- markup below 300KG - *1.75, 301 to 500KG - *1.55, 501 to 1000KG - *1.50

5. If the destination is USA, South Africa or Nigeria and weight is above (400KG) .......add a box ( X) I agree that GCL custom broker team can contact me to offer destination charges (customs clearance & delivery to Door).  via email or mobile. please enter destination address. 

ANY QUESTION - Hit me? 

[ATA_EXCEL_Feb19 (1).zip](https://github.com/mayank30/gclparcel/files/2985349/ATA_EXCEL_Feb19.1.zip)

**Comment by mayank30** [comment]
is now backend driven and can be managed by Admin, 

Closing the tickets ,..

**Comment by ambroseIT** [comment]
No - this is a new requirent.

YOu need to read it properly. Open it back. We will fix this in the next phase.
