### ISSUE TITLE
General - Nigeria Cities & States

### ISSUE THREAD

**Issue by ambroseIT** [mayank30/gclparcel#16]
Please see the attached for
1. Nigeria city & States.

> Transport charges included 

> 

2. UK Pick up Charges & UK delivery Charges -  (Agent & Individual )
3. UK To Europe Charges -  (Agent & Individual )
 
[Countries.xlsx](https://github.com/mayank30/gclparcel/files/2989751/Countries.xlsx)

**Comment by mayank30** [comment]
Need to discuss will connect over call ??

**Comment by ambroseIT** [comment]
I will be available UK time 7pm evening to 8am morning mon - fri. sat & sun all day. 

Let get this project completed, please.
