### ISSUE TITLE
Express -  Package Details show x 3 time in Error

### ISSUE THREAD

**Issue by ambroseIT** [mayank30/gclparcel#18]
I attended booking a package. 
1. Entered dims from Get a quote and I got a price.  1 pc 50x40x40 50kg.

> ERROR
The system on it own showed the dims 3 times and increased the total weight to 150KG  & updated the price. It shouldn't do that...

1 pc 50x40x40 50kg.
1 pc 50x40x40 50kg.
1 pc 50x40x40 50kg.

> Booking multiple packages above 60KG.
1. Yes you can book 1000KG via DHL but each piece must be less than 70KG.
2. In our own case, each piece must be less than 60KG.
3. You can then have 60Kg x 16 pcs and 30KG x 1 pcs.

**Do you understand my explanation?**
![C7F580BF-534C-48B3-82C7-A83A940D4F5E](https://user-images.githubusercontent.com/10438260/55275320-5a227080-52dc-11e9-9e59-af4d89fb9acb.jpg)
![709EA3DA-F28A-4F86-B6E9-AE41B1EE6C2F](https://user-images.githubusercontent.com/10438260/55275321-5a227080-52dc-11e9-95fd-4f371d75a7a2.jpg)

**Comment by ambroseIT** [comment]
this issue has occurred.

I entered 1 parameter.

![image](https://user-images.githubusercontent.com/10438260/58599256-62187580-8277-11e9-80ba-7cf728d0ea75.png)

**Comment by mayank30** [comment]
Fixed and deployed
