### ISSUE TITLE
Express Validate Address page

### ISSUE THREAD

**Issue by ambroseIT** [mayank30/gclparcel#2]
1.You have all the UK postcode and city. Once the UK enters postcode Please populate it.
2. Correct to Shipper Adress not Shipping Address.
3. Address Book missing - the user should be able to save both Shipper and consignee to Shipper Address book & Consignee Address book. So that they can re-use in the future. The address can be given Nice names for easy identification by user. - 
4. Shipper Section - Should have a tick box to set as default my Home Address, Office Address 
5. Phone NUmber: Country postcode missing based on the country select, please. 

Comment: The layout is clean and fine.

**Comment by mayank30** [comment]
i dont have UK Postcode and city

**Comment by ambroseIT** [comment]
I sent this to you Nov 28. Please check your skype. I am resending it.
Create a table called UK Postcode and insert this data, please.  
[UK POSTCODES.zip](https://github.com/mayank30/gclparcel/files/2974976/UK.POSTCODES.zip)

**Comment by ambroseIT** [comment]
General Address format 
1. Address line 1, 2...................... you can add line 3 to African countries. check dhl toolkit for African region countries.
2. Postcode .......... used to determine locality. 
3.  city/town.......... same data as locality 
4. county ......... in other countries it called state........ in Canada it called provinces. 
5. Country.

**Comment by mayank30** [comment]
I am sure sure what you mean and you are talking about ...

**Comment by ambroseIT** [comment]
I sent you UPS and DHL Address Format ...showing all lines. Make sure you replicate, please. That all you need.

**Comment by mayank30** [comment]
Code Done .. !! Avaiable in next test release ,...

**Comment by ambroseIT** [comment]
Agreed - Good Job mate :) working fine.. Although it was a fight for you to get it to that state.
