### ISSUE TITLE
Air CArgo - Package Restriction

### ISSUE THREAD

**Issue by ambroseIT** [mayank30/gclparcel#22]
Document - 10KG 
Pallet - No weight restriction (160 cm high)
parcel - 1- 50KG per single shipment. You can have a Total of 200 but divided into 4 places

**Comment by mayank30** [comment]
From front screen we will do validation .. for Document &  Pallet 
But for Parcel.. we will don;t allowed weight restriction .. but inner page .. when user enter Package details at that time we will only allowed maximum weight of 50 Kgs per pieces.

**Comment by ambroseIT** [comment]
1. Pallet 200KG. Restriction not working well. please investigate.

![image](https://user-images.githubusercontent.com/10438260/64927945-470f4880-d809-11e9-94de-bed0087eeec7.png)

I entered 160 x 200 x 200 200KG 

The restriction is on Height 160 cm not width

![image](https://user-images.githubusercontent.com/10438260/64927960-8a69b700-d809-11e9-99c8-ad367949c2e9.png)

Now i entered 
150 x150 x150 200kg
![image](https://user-images.githubusercontent.com/10438260/64927967-ab320c80-d809-11e9-9c80-de66fcd9acfa.png)

Got warning that pallet should not be more than 50KG
![image](https://user-images.githubusercontent.com/10438260/64927971-be44dc80-d809-11e9-83fa-13318a00cca1.png)


----------------------------

This issue was fixed before not sure why it has come back......Please fix
Document - 10KG
Pallet - No weight restriction............ (160 cm high)
parcel - 1- 50KG per single shipment. You can have a Total of 200 but divided into 4 places

**Comment by ambroseIT** [comment]
Declared Weight doesn't get updated ...when you delete /....STOPPED can't proceed with the booking 

![image](https://user-images.githubusercontent.com/10438260/64928078-07e1f700-d80b-11e9-8196-94789e67fa87.png)
