### ISSUE TITLE
Air Cargo - UK to EU / USA / Canada  (Remote Area Charge)

### ISSUE THREAD

**Issue by ambroseIT** [mayank30/gclparcel#25]
HI,

  I compared our rate UK office to Spain with DHL rate.

I found out DHL rate was more than the rate loaded for Agent. 
1. Our Rate 
![image](https://user-images.githubusercontent.com/10438260/58598088-bcfb9e00-8272-11e9-9b6a-4e9c525e226f.png)

2. DHL rate
![image](https://user-images.githubusercontent.com/10438260/58597924-07c8e600-8272-11e9-8940-75fec5d57fba.png)

When I investigated further I found out that the postcode example I used was a remote area. 
The remote area has an extra charge. 
DHL charges £17.50

> Propose
We will need to load remote area postcode and city into a table called Remote Area. You can have a country, postcode, city, No_postcode (Y/N) .

1. For 1- 50KG
GCL Individual £25 
GCL Agent £22.50

2. For 51Kg above 
GCL Individual £0.75/kg
GCL Agent £0.55/kg

- [ ]  Remote Area 
https://www.dhl.com/content/dam/downloads/g0/express/services/surcharges/dhl_express_remote_areas.pdf 
- [ ]  Remote Charges 
![image](https://user-images.githubusercontent.com/10438260/58598608-f9c89480-8274-11e9-8131-e1e447841e1c.png)

Comparing 1000kg
1. DHL 
![image](https://user-images.githubusercontent.com/10438260/58598482-82930080-8274-11e9-9a11-c06813dc9918.png)

2. GCL 
![image](https://user-images.githubusercontent.com/10438260/58598505-95a5d080-8274-11e9-86e3-939b4c51494a.png)

**Comment by mayank30** [comment]
Can be manage from backend panel. you can edit .. it
