### ISSUE TITLE
Express / Air Cargo - Pick Up Details

### ISSUE THREAD

**Issue by ambroseIT** [mayank30/gclparcel#27]
1. GCL 
![image](https://user-images.githubusercontent.com/10438260/58600734-ae66b400-827d-11e9-9fd1-72f7116465b6.png)

2. DHL Formart 
![image](https://user-images.githubusercontent.com/10438260/58600778-d5bd8100-827d-11e9-9228-99dcd5d85b95.png)

> What is Key in the above are:
1. Pick Up window 
2. note: Please allow at least 120 minutes for your Pickup Window
The latest time a request can be made for pickup today is 3:00 pm
3. Disclaimer 
Disclaimer and Important Details
The courier will attempt to collect during your pickup window times and before your business closes.
However, should there be circumstances beyond the courier's control, the pickup might be later than your close time.
If Shipment is not in the right packaging the courier could refused to pick up and you will have to give us a call immediately for advice. (single shipment above 50kg must be palletized)

**Comment by mayank30** [comment]
@ambroseIT 

I don't understand this part .
