### ISSUE TITLE
Package Details

### ISSUE THREAD

**Issue by ambroseIT** [mayank30/gclparcel#3]
Rearrange the dims...
1. Please move the pre-populated dims up and the Add pics should be below, please. 
2. Declare Value - Do not hard code value.. Let the user enter the value...if they don't show error. (Enter Value).
3. The insurance section - will need to be reviewed once we have an insurance provider.

**Comment by mayank30** [comment]
I have fixed it will be part of next release.

**Comment by ambroseIT** [comment]
Awaiting testing once you have installed the new released

**Comment by ambroseIT** [comment]
Agreed - thanks
