### ISSUE TITLE
Express - Parcel Details Duplication in Error

### ISSUE THREAD

**Issue by ambroseIT** [mayank30/gclparcel#32]
1. If a user submits 1 parcel - Do not duplicate and overcharge, please.

2. Users should be allowed to create Duplicates parcel.

![image](https://user-images.githubusercontent.com/10438260/63008385-703f6080-be7a-11e9-9dba-365e5a6dcf32.png)

**Comment by mayank30** [comment]
Not it fixed.-- code deployed.
