### ISSUE TITLE
Express - Get quote - Need meaningful  Error Message 

### ISSUE THREAD

**Issue by ambroseIT** [mayank30/gclparcel#33]
If User Enters wrong postcode or postcode format - Give a meaningful Error to the user or color on the parameter box if you can. 
![image](https://user-images.githubusercontent.com/10438260/63008671-fbb8f180-be7a-11e9-91b3-6858731f0ab6.png)

The dims works fine - When you enter an Alpha value - it gives a meaningful error

**Comment by ambroseIT** [comment]
You can find DHL error code and meanings in the toolkit

![image](https://user-images.githubusercontent.com/10438260/63010145-bea22e80-be7d-11e9-92b3-b9edd86c5393.png)

Attached is a file within the toolkit (http://xmlpitest-ea.dhl.com/toolkit/Toolkit.zip) and it has the tab Error Messages, this should show more detail.

Create and Load Up a Error Message table.

**Comment by mayank30** [comment]
See we have few things on client side as validation .. 

but the error are from DHL server .. we have already handled it ..

Now Quote API will be handling Error from DHL
