### ISSUE TITLE
Expree / Air Cargo : Quotation Display - Header missing

### ISSUE THREAD

**Issue by ambroseIT** [mayank30/gclparcel#38]
We need to put a good header for users to understand- Please pay attention to these details and make the UI font professional.
1. Estimate Delivery Date
2. Estimated Price 
3. Service Type

![image](https://user-images.githubusercontent.com/10438260/64135231-0d3c4c00-cdde-11e9-8efa-79be196b2377.png)

![image](https://user-images.githubusercontent.com/10438260/64135217-ed0c8d00-cddd-11e9-921d-bf75e29c1a7e.png)

when user expands to know the details of the quote
![image](https://user-images.githubusercontent.com/10438260/64135247-3e1c8100-cdde-11e9-89ee-16b3a95cf016.png)

I am not saying you should do exactly because I know you will start saying am changing the design. I am only showing you how DHL has done theirs. And they have done it for a reason....people like to know breakdown of what they are buying.

**Comment by mayank30** [comment]
Done
