### ISSUE TITLE
Express: Documentation Header - Amend Consignee to Transfer Via 

### ISSUE THREAD

**Issue by ambroseIT** [mayank30/gclparcel#39]
1. Edit Consignee  to Transfer Warehouse

2. Routing: (Shipper city or postcode) - (GCL City) - (Receivers city or postcode)
e.g M11- MAN - TEMA

![image](https://user-images.githubusercontent.com/10438260/64135382-ba639400-cddf-11e9-8ab8-4f5d9e459c50.png)

**Comment by ambroseIT** [comment]
Add that line ..

Routing: (Shipper half PostCode - MAN - Destination City/Postcode)

E.g. Routing: M11 - MAN - TEM

**Comment by mayank30** [comment]
Done .. defined the logic. ...
