### ISSUE TITLE
Pick Details

### ISSUE THREAD

**Issue by ambroseIT** [mayank30/gclparcel#4]
1. Pick Up Date - please introduce a calendar so that user just select a date and you populate the date in the format that is correct.

**Comment by mayank30** [comment]
This is not possible .. at this moment

**Comment by ambroseIT** [comment]
have you got a better idea on how you want to handle the date formatting then? Because it a system bug.
When you have 11-3-2019, the system is throwing error message out. You don't expect used to be editing the calendar by putting "0" in front of the month.

**Comment by mayank30** [comment]
I have updated date .. and prepend zero to it .. will be avaible in next release. ..
