### ISSUE TITLE
Address: Contact US Update 

### ISSUE THREAD

**Issue by ambroseIT** [mayank30/gclparcel#43]
Hi,
Edit Please

****
![image](https://user-images.githubusercontent.com/10438260/64327167-27834f00-cfc3-11e9-9d39-11bd87efcc6c.png)

![image](https://user-images.githubusercontent.com/10438260/64327236-4255c380-cfc3-11e9-8888-a34c1eed5a01.png)

**Comment by ambroseIT** [comment]
GCL Parcel Inc. - For Mailing Only
Global Corporate Logistics LTD UK
285 Moorside Road
Swinton
Manchester M27 9PJ

**Comment by mayank30** [comment]
Done updated .. map also updated for you

**Comment by ambroseIT** [comment]
![image](https://user-images.githubusercontent.com/10438260/64493918-39dce180-d27e-11e9-841e-89a973e6305c.png)


remove the foreign language plz
