### ISSUE TITLE
Profile Address:  Use UK Shipper Address To Create Profile Address 

### ISSUE THREAD

**Issue by ambroseIT** [mayank30/gclparcel#46]
![image](https://user-images.githubusercontent.com/10438260/64377268-fab25480-d021-11e9-89a8-9b1847379c7a.png)

We just need a tick box

![image](https://user-images.githubusercontent.com/10438260/64374440-cb004e00-d01b-11e9-8485-62cb5a7c1773.png)

Add a Tick box - 

![image](https://user-images.githubusercontent.com/10438260/64375221-59c19a80-d01d-11e9-848c-865efd0fb550.png)

**Comment by mayank30** [comment]
We already have address book 
http://164.68.110.82:8080/my-address-book

**Comment by mayank30** [comment]
But added section there too

**Comment by ambroseIT** [comment]
put we need to have the user profile ..... name & address since our login method is a smart logic. What do you say to that? 

A flag to say... Yees it my residential address is not too much.
