### ISSUE TITLE
Air Freight / Express / Sea : Disclaimer Before Payment Terms and Condition 

### ISSUE THREAD

**Issue by ambroseIT** [mayank30/gclparcel#47]
Hi,

Insert : 
Terms and Conditions
By clicking ACCEPT – I accept GCL's Terms and Conditions of Carriage and declare that this shipment does not include any Prohibited Items .

![image](https://user-images.githubusercontent.com/10438260/64377600-b3789380-d022-11e9-9b42-de659a7c6657.png)

![image](https://user-images.githubusercontent.com/10438260/64377657-cdb27180-d022-11e9-9ee1-79d47ff62e90.png)

**Comment by ambroseIT** [comment]
Terms & Condition: http://164.68.110.82:8080/terms-of-use 

Prohibited: https://www.globalcorporatelogistics.com/prohibited-items/

[GCL   Prohibited items.txt](https://github.com/mayank30/gclparcel/files/3581078/GCL.Prohibited.items.txt)

**Comment by mayank30** [comment]
http://164.68.110.82:8080/prohibited-items --> new page created backend driven can be manage by admin.. 

Terms of use will be linked as mention before payment.

**Comment by mayank30** [comment]
![image](https://user-images.githubusercontent.com/6511688/64451847-ae8b1100-d102-11e9-861a-01538a514a89.png)
