### ISSUE TITLE
Back/Previous:    Air freight / Express Order Process

### ISSUE THREAD

**Issue by ambroseIT** [mayank30/gclparcel#48]
We need Back / Previous across all pages....

![image](https://user-images.githubusercontent.com/10438260/64378189-0acb3380-d024-11e9-8502-ee0ac113ff7a.png)

**Comment by mayank30** [comment]
Instead, we don't encourage to have back and previous button as it is not slide show .. 
though the functionality was still there ... you can go on any step by click on any circle on blue bar ..
