### ISSUE TITLE
Express - Confirm & Pay

### ISSUE THREAD

**Issue by ambroseIT** [mayank30/gclparcel#5]
1. Message - why do you have £ need to the details entered. 
2. Confirm and Pay button - Not working

**Comment by mayank30** [comment]
Confirm and Pay button - is now working. 
Message - why do you have £ need to the details entered.  -- > elaborate more ,.. not able to understand

**Comment by mayank30** [comment]
Message - why do you have £ need to the details entered. -- > elaborate more ,.. not able to understand

Removed before confirm and pay button .. 

also Now .. Exchange Rates are backend driven 

So Confirm, and Pay will never broken ..
