### ISSUE TITLE
Nigeria (Air Cargo & Express) GUI must be the same 

### ISSUE THREAD

**Issue by ambroseIT** [mayank30/gclparcel#50]
1. This is OK
![image](https://user-images.githubusercontent.com/10438260/64381505-40bfe600-d02b-11e9-979d-83f57a011779.png)

2. You need to replicate the above .....ASAP 
![image](https://user-images.githubusercontent.com/10438260/64381418-0bb39380-d02b-11e9-9b50-0ad9d9f9b74b.png)

**Comment by mayank30** [comment]
Done
