### ISSUE TITLE
Insurance: Express / Air Cargo 

### ISSUE THREAD

**Issue by ambroseIT** [mayank30/gclparcel#53]
1. Express
From: Nigeria & UK 
- The standard charge of Shipment Insurance for Express
documents and parcels is 5% of the actual value of the
goods you have declared (subject to a minimum charge
of £22.00 GBP). 

HIGH-VALUE COVER: 
For shipments with an insurance value over £10,000,
please contact GCL Customer Service on 07577833627
quoting “High Value Authorisation”.

2. Air Cargo
From Nigeria to Any country - put ........ Insurance: Not available for this route.
From the UK to other countries different from Nigeria .....use as logic as Express.

**Comment by mayank30** [comment]
Mark it as enhancement will consider it later ..

**Comment by mayank30** [comment]
Only update by default 5% of declared value & min is 22 GBP

**Comment by ambroseIT** [comment]
Air Cargo once route shows Nigeria.....................Please disable......I have no insurance provider for Nigeria. i will enable in future........For this Go Live disable insurance please......
![image](https://user-images.githubusercontent.com/10438260/64493309-76a4da80-d276-11e9-8ca1-84ddae435251.png)

**Comment by ambroseIT** [comment]
![image](https://user-images.githubusercontent.com/10438260/64644904-9e797700-d40b-11e9-95bc-937e978240e1.png)

**Comment by ambroseIT** [comment]
Insurance - text required at the summarry page 

Message - section ... Export reason missing... same as Express please

![image](https://user-images.githubusercontent.com/10438260/64732627-077bf000-d4db-11e9-90b5-4191b45472fe.png)
