### ISSUE TITLE
Order Confirmation (Express / AIr Cargo)

### ISSUE THREAD

**Issue by ambroseIT** [mayank30/gclparcel#54]
Current - Thank you for ordering with us for placing your order, We received your order and we will let you know when we ship it out.            

Thank you for your booking. Please print your shipping label before the courier arrives. 

![image](https://user-images.githubusercontent.com/10438260/64480621-d346bd80-d1c2-11e9-95d3-60c1de144a1a.png)

**Comment by mayank30** [comment]
Done
