### ISSUE TITLE
Express DOcs : COrrection Pick Up LAbel should not have commercial Generated.

### ISSUE THREAD

**Issue by ambroseIT** [mayank30/gclparcel#56]
Remember we have 2 stages for Express Indirect.
1. UK Pick UP - (Pick up label & Order Receipt Only)
2. the International Booking. (DHL Export doc & commercial invoice)

Display only Pick Up label and Order Invoice at this stage only. Also, change the logo from DHL to GCL logo.

Once we have the `parcel and rebook then the new DHL International doc will be uploaded. 
- DHL Express label to the final destination and commercial invoice will now appear. 

![image](https://user-images.githubusercontent.com/10438260/64480845-8fa28280-d1c7-11e9-9027-d527d621c532.png)

**Comment by mayank30** [comment]
See I don't understand your commnet, but i am sure the DHL Doc we are showcasing is Transfer to your GCL UK office from Source, and Invoice has end to end details 

apart from that 
I have updated logo next build will have new logo going forward.

**Comment by ambroseIT** [comment]
When you are just generating UK pick Up.............commercial invoice is not required at that time......it will confuse the courier driver picking the parcel.

> Leg 1 ..

..Only generate 
1. UK Pick to transfer warehouse  _(this will be printed out & giving to the driver by sender)_
and
2. GCL payment receipt 


when shipment get to GCL UK warehouse...then we will generate leg 2

> Leg 2 needs

1. the Internal waybill to final destination showing (senders address & final destination address)
2. commercial invoice 
_(both  will be printed out & giving to the driver by Admin team)_
