### ISSUE TITLE
Sea Freight : All Text Need to be loaded and correction in the docs

### ISSUE THREAD

**Issue by ambroseIT** [mayank30/gclparcel#58]
![image](https://user-images.githubusercontent.com/10438260/64485868-8f34d680-d21d-11e9-9ca1-a550834443af.png)

**Comment by mayank30** [comment]
can u provide me document link

**Comment by ambroseIT** [comment]
you have access to this document as it was shared with you ages ago. 
![image](https://user-images.githubusercontent.com/10438260/64493041-f6c94100-d272-11e9-969c-026fa38a61aa.png)


https://docs.google.com/document/d/1ao4JB9Mw9xBLQJ6d1cDV6fRLOW_IfUXd52g-NM0FzW4/edit

**Comment by ambroseIT** [comment]
FCL - after you submit a request ..
![image](https://user-images.githubusercontent.com/10438260/65392590-6c9ed380-dd6e-11e9-81c9-64004a8c18bb.png)


![image](https://user-images.githubusercontent.com/10438260/65392601-83452a80-dd6e-11e9-8429-f3588745bd64.png)

![image](https://user-images.githubusercontent.com/10438260/65392626-aff94200-dd6e-11e9-85c1-616aea66d9e4.png)

![image](https://user-images.githubusercontent.com/10438260/65392662-08c8da80-dd6f-11e9-95ee-394e75ef46af.png)



Both Express air cargo and sea ...... Final page should have Do you want to book New Parcel etc...and that takes use to the start if they want to book a new order. then the flow starts again

**Comment by mayank30** [comment]
Fix and Closing this !!
