### ISSUE TITLE
Air Cargo Admin: To Nigeria..... Lock it Down (GCL Nig Location)

### ISSUE THREAD

**Issue by ambroseIT** [mayank30/gclparcel#59]
After analysing the price i can see no logic to manage from Nigeria office to (all states in Nigeria). 

Since we have No time - Lock it down to my lagos office. Quicker solution - make it Collection Service. 

Nig GCL Office to Nig Anywhere - Not FOund

![image](https://user-images.githubusercontent.com/10438260/64491292-e018ef00-d25e-11e9-9b0c-02fd948460fb.png)

![image](https://user-images.githubusercontent.com/10438260/64491337-85cc5e00-d25f-11e9-97cd-078710a33524.png)

**Comment by ambroseIT** [comment]
Whichever is quicker please.....................You can either Do Door delivery or Collection Service 

![image](https://user-images.githubusercontent.com/10438260/64491414-47836e80-d260-11e9-9449-f5348a6d75f6.png)

**Comment by mayank30** [comment]
No that is not possible to change the logic at this moment

**Comment by ambroseIT** [comment]
We are not changing logic...........You forgot to add the delivery rate i gave you.............so find the quickest way around it.........either you just lock it down to my Lagos office........so people collect from my lagos office only................I prefer that. 

Or you add the delivery charges to other sites........


we had this done previously................not sure how you lost the code.

If you remember i told you to group it as..
1. Lagos Mainland 
2. Lagos Island 
3. Outside Lagos. (all cities outside lagos falls in this category)
Check the country rate sheet you have..........

See for example 30 KG to Nigeria Lagos should not be the same to Abuja or Aba for example. 

![image](https://user-images.githubusercontent.com/10438260/64493151-5542ef00-d274-11e9-8466-9e72503f71ff.png)
