### ISSUE TITLE
Air Cargo - Get Quote

### ISSUE THREAD

**Issue by ambroseIT** [mayank30/gclparcel#6]
1. Select Package Type - force user to identify
2. Load Nigeria cities to To city, please. remove the dummy city used. 
3. Nigeria to EU - not displaying quote 
4. Nigeria to USA - not displaying quote 
5. Nigeria to UK - not working 
6. Embed - Google API to the postcode please for Air Cargo.

**Comment by mayank30** [comment]
Done Code fix .. will deploy on next release ..
