### ISSUE TITLE
Customer Service: Frequently asked question

### ISSUE THREAD

**Issue by ambroseIT** [mayank30/gclparcel#60]
Edit..

![image](https://user-images.githubusercontent.com/10438260/64492956-1318ae00-d272-11e9-9ede-674c9c739b96.png)

[GCL PARCEL FAQ - clean version.docx](https://github.com/mayank30/gclparcel/files/3587914/GCL.PARCEL.FAQ.-.clean.version.docx)

**Comment by mayank30** [comment]
Done
