### ISSUE TITLE
Air Cargo once route shows Nigeria.....................Please disable......I have no insurance provider for Nigeria. i will enable in future........For this Go Live disable insurance please......

### ISSUE THREAD

**Issue by ambroseIT** [mayank30/gclparcel#62]
Air Cargo once route shows Nigeria.....................Please disable......I have no insurance provider for Nigeria. i will enable in future........For this Go Live disable insurance please......
![image](https://user-images.githubusercontent.com/10438260/64493309-76a4da80-d276-11e9-8ca1-84ddae435251.png)

_Originally posted by @ambroseIT in https://github.com/mayank30/gclparcel/issues/53#issuecomment-529233714_

**Comment by mayank30** [comment]
Do you mean that if we ship to nigeria then it will be always without insurance. ??

**Comment by mayank30** [comment]
Done

**Comment by ambroseIT** [comment]
![image](https://user-images.githubusercontent.com/10438260/64644936-af29ed00-d40b-11e9-90f2-45a19c8c1721.png)
