### ISSUE TITLE
Account Holder User profile ..... name & address  is needed for security purpose. 

### ISSUE THREAD

**Issue by ambroseIT** [mayank30/gclparcel#63]
put we need to have the user profile ..... name & address since our login method is a smart logic. What do you say to that? 

A flag to say... Yees it my residential address is not too much.

_Originally posted by @ambroseIT in https://github.com/mayank30/gclparcel/issues/46#issuecomment-529233965_

**Comment by ambroseIT** [comment]
We need a flag for user to tick - My Residential Address. 
![image](https://user-images.githubusercontent.com/10438260/64516098-ca024180-d2e5-11e9-9363-82288fbac1d1.png)

**Comment by mayank30** [comment]
for you its just a flag, but the same address book is used by DHL api and due to which if i alter any object that will not validate by DHL api and express will be broken seems need to deal differently ..

will talk it later and hence mark it as enhancement.

**Comment by mayank30** [comment]
Done
