### ISSUE TITLE
Air Cargo: PIck Up message Not coming across

### ISSUE THREAD

**Issue by ambroseIT** [mayank30/gclparcel#64]
Hi,

The pick up message to courier was Front Door. 

![image](https://user-images.githubusercontent.com/10438260/64493392-71945b00-d277-11e9-9f15-6b003112e05a.png)

1. The pick up date and time in schedule page was perfect 2019-09-09 next working date bu the summary show sysdate date today sunday 
2. rearrange:
a. shipper details
b. transfer warehouse 
c. consignee

3. routing: M27 - M11 - LOS 
![image](https://user-images.githubusercontent.com/10438260/64493428-3d6d6a00-d278-11e9-8400-9fceb892635a.png)

**Comment by mayank30** [comment]
Done 

Will be avaiable in next build
