### ISSUE TITLE
Sea Freight : Text Upload like Marsk line - For Standard 

### ISSUE THREAD

**Issue by ambroseIT** [mayank30/gclparcel#68]
You can log into maersk line but do not book any shipment - it live please. 
![image](https://user-images.githubusercontent.com/10438260/64726966-a7cc1780-d4cf-11e9-9344-0f4e975f2691.png)

user: KJSHIPPING 
PAss: Melvin17

https://www.maersk.com/instantPrice/

![image](https://user-images.githubusercontent.com/10438260/64726702-1bb9f000-d4cf-11e9-9490-57ae9524c0e3.png)

**Comment by ambroseIT** [comment]
once the user Company & personal Address is known and saved ..... no need to Show that company section Again...................

You can see when you log in to maersk line


![image](https://user-images.githubusercontent.com/10438260/64731709-9ab42600-d4d9-11e9-8880-40eed7d7e980.png)

**Comment by mayank30** [comment]
Done
