### ISSUE TITLE
Sea Freight : Text Upload like Marsk line - For  Oversize Cargo

### ISSUE THREAD

**Issue by ambroseIT** [mayank30/gclparcel#69]
You can log into maersk line but do not book any shipment - it live please. 
![image](https://user-images.githubusercontent.com/10438260/64726966-a7cc1780-d4cf-11e9-9344-0f4e975f2691.png)

user: KJSHIPPING 
PAss: Melvin17

https://www.maersk.com/instantPrice/

...............
![image](https://user-images.githubusercontent.com/10438260/64727546-fd54f400-d4d0-11e9-91f6-9f619f1b69dd.png)

**Comment by mayank30** [comment]
Done
