### ISSUE TITLE
Sea Freight : Text Amend- Some Important Notes

### ISSUE THREAD

**Issue by ambroseIT** [mayank30/gclparcel#70]
![image](https://user-images.githubusercontent.com/10438260/64728712-879e5780-d4d3-11e9-8f85-414ff3521207.png)

Some Important Notes
How does it work?

- Any quote requests for long term validity, please contact your local office: https://www.globalcorporatelogistics.com/contactus/

- Please do not enter personal or financial information, such as phone numbers, credit card details, or debit card details anywhere in your request.

- Please note that when you submit your quote request, an automated confirmation e-mail will be sent to you containing the details you entered in this form.

- Forwarder requesting quote on behalf of other customers (Named Account Customer), Government Cargo, US Flag please reach out to your sales contact.

Please note that we are unable to provide services to the following countries. Seria, Russia, Yemen, Sudan, Iraq, Cuba, north Korea, Venezuela

**Comment by mayank30** [comment]
Done
