### ISSUE TITLE
Insurance - text required at the summarry page

### ISSUE THREAD

**Issue by ambroseIT** [mayank30/gclparcel#73]
Insurance - text required at the summarry page 

Message - section ... Export reason missing... same as Express please

![image](https://user-images.githubusercontent.com/10438260/64733528-d997ab00-d4dc-11e9-811f-56b1690980f4.png)

_Originally posted by @ambroseIT in https://github.com/mayank30/gclparcel/issues/53#issuecomment-530552284_

**Comment by mayank30** [comment]
Done

**Comment by ambroseIT** [comment]
cool
